[build]
  publish = "public/"
  command = "npm run build"

[[plugins]]
  # Installs the Lighthouse Build Plugin for all deploy contexts
  package = "@netlify/plugin-lighthouse"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = false
  minify = true
[build.processing.js]
  bundle = false
  minify = true
[build.processing.images]
  compress = true
[build.processing.html]
  pretty_urls = false

[[redirects]]
  from = "/order"
  to = "https://epay.gatech.edu/C20793_ustores/web/product_detail.jsp?PRODUCTID=5791"
  status = 301
  force = true

[[redirects]]
  from = "/ads"
  to = "https://epay.gatech.edu:443/C20793_ustores/web/store_cat.jsp?STOREID=559&CATID=672"
  status = 301
  force = true
